---
name: unittest
on: [push, pull_request]

jobs:
  unittest:
    name: "${{ matrix.config.name }} - Boost ${{ matrix.boost_version }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        boost_version: ["1.75.0", "1.76.0", "1.77.0", "1.78.0", "1.79.0"]
        config:
          - {
            name: "MSVC 2022 (Debug)",
            os: windows-2022,
            build_args: "--config Debug",
            test_args: "-C Debug"
            }
          - {
            name: "MSVC 2022 (Release)",
            os: windows-2022,
            build_args: "--config Release",
            test_args: "-C Release"
            }
          - {
            name: "MSVC 2019 (Toolset 141, Debug)",
            os: windows-2019,
            config_args: "-T v141",
            build_args: "--config Debug",
            test_args: "-C Debug"
            }
          - {
            name: "MSVC 2019 (Toolset 141, Release)",
            os: windows-2019,
            config_args: "-T v141",
            build_args: "--config Release",
            test_args: "-C Release"
            }
          - {
            name: "MSVC 2019 (Toolset 142, Debug)",
            os: windows-2019,
            config_args: "-T v142",
            build_args: "--config Debug",
            test_args: "-C Debug"
            }
          - {
            name: "MSVC 2019 (Toolset 142, Debug, Unicode)",
            os: windows-2019,
            config_args: "-T v142",
            build_args: "--config Debug -- -p:CharacterSet=Unicode",
            test_args: "-C Debug"
            }
          - {
            name: "MSVC 2019 (Toolset 142, Release, Unicode)",
            os: windows-2019,
            config_args: "-T v142",
            build_args: "--config Release -- -p:CharacterSet=Unicode",
            test_args: "-C Release"
            }
          - {
            name: "MSVC 2019 (Toolset 142, Release)",
            os: windows-2019,
            config_args: "-T v142",
            build_args: "--config Release",
            test_args: "-C Release"
            }
          - {
            name: "ClangCL (Windows 2019)",
            os: windows-2019,
            config_args: "-T ClangCL"
            }
          - {
            name: "MinGW (Windows 2019)",
            os: windows-2019,
            config_args: "-G MinGW Makefiles"
            }
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        boost_version: ${{ matrix.boost_version }}
        platform_version: 2019
        arch: null
    - name: Add boost path
      run: echo "BOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}" >> $env:GITHUB_ENV
    - name: Install packages
      run: cinst openssl
    - name: Configure
      env:
        CMAKE_ARGS: ${{ matrix.config.config_args }}
      shell: bash
      run: cmake -B build -DENABLE_DOCUMENTATION=OFF "${CMAKE_ARGS}"
    - name: Build
      env:
        CMAKE_ARGS: ${{ matrix.config.build_args }}
      shell: bash
      run: cmake --build build/ ${CMAKE_ARGS}
    - name: Run tests
      env:
        CTEST_ARGS: ${{ matrix.config.test_args }}
      shell: bash
      run: ctest --output-on-failure ${CTEST_ARGS}
      working-directory: build/
